name: Deploy

on:
  push:
    branches:
      - master

jobs:
  trigger_ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pez-ansible deploy
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: rwejlgaard
          repo: pez-ansible
          github_token: ${{ secrets.AUTH_TOKEN }}
          workflow_file_name: apply.yml
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true